version: '3'
services:
  source-kinesis:
    image: python:3.9-slim
    volumes:
      - ./source_kinesis.py:/app/source_kinesis.py
    command: python /app/source_kinesis.py
  
  sink-dynamodb:
    image: python:3.9-slim
    volumes:
      - ./sink_dynamodb.py:/app/sink_dynamodb.py
    command: python /app/sink_dynamodb.py

  producer:
    image: python:3.9-slim
    volumes:
      - ./producer.py:/app/producer.py
    command: python /app/producer.py
  
  consumer:
    image: python:3.9-slim
    volumes:
      - ./consumer.py:/app/consumer.py
    command: python /app/consumer.py
